apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: c2VjdXJlcGFzc3dvcmQ= # "securepassword" base64 encoded
  mysql-password: d29yZHByZXNzcGFzc3dvcmQ= # "wordpresspassword" base64 encoded
sops:
# SOPS encryption metadata will be added during encryption process