apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressUsername: admin
    wordpressPassword: adminpassword
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql
      user: wordpress
      password: wordpresspassword
      database: wordpress
    ingress:
      enabled: true
      hostname: app.local
      annotations:
        kubernetes.io/ingress.class: nginx